# Secret: Keycloak Admin Credentials
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: cloud-app
stringData:
  password: admin-password

---
# Secret: Database Credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: cloud-app
stringData:
  url: mysql://user:password@cloud-app-mariadb:3306/appdb
