apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: cloud-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard